# Generated by Django 5.2.8 on 2025-11-10 09:51

import django.db.models.deletion
from django.db import migrations, models


def copy_group_data(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    for student in Student.objects.all():
        if hasattr(student, 'group'):
            student.group_old = student.group
            student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(copy_group_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.faculty')),
            ],
            options={
                'unique_together': {('name', 'faculty')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group'),
        ),
    ]
