# Generated by Django 5.2.8 on 2025-11-10 09:54

from django.db import migrations


def migrate_group_data(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    Group = apps.get_model('core', 'Group')
    
    students_with_old_groups = Student.objects.exclude(group_old__isnull=True).exclude(group_old='')
    
    for student in students_with_old_groups:
        if student.faculty and student.group_old:
            group, created = Group.objects.get_or_create(
                name=student.group_old,
                faculty=student.faculty
            )
            student.group = group
            student.save()


def reverse_migrate(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    
    for student in Student.objects.exclude(group__isnull=True):
        if student.group:
            student.group_old = student.group.name
            student.group = None
            student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_group_field'),
    ]

    operations = [
        migrations.RunPython(migrate_group_data, reverse_migrate),
    ]
