# Generated by Django 5.2.8 on 2025-11-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migrate_old_group_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_old',
        ),
    ]
